export let addAnimeFormInputs = [
  {
    label: "Title",
    inputType: "text",
    placeholder: "",
    required: true,
    value: "",
  },
  {
    label: "Title (English)",
    inputType: "text",
    placeholder: "",
    required: false,
    value: "",
  },
  {
    label: "MAL Link",
    inputType: "text",
    placeholder: "",
    required: false,
    value: "",
  },
  {
    label: "Img URL",
    inputType: "text",
    placeholder: "",
    required: false,
    value: "",
  },
  {
    label: "Seasons",
    inputType: "number",
    placeholder: "",
    required: false,
    value: "",
  },
  {
    label: "Episodes",
    inputType: "number",
    placeholder: "",
    required: false,
    value: "",
  },
  {
    label: "Status",
    inputType: "text",
    placeholder: "",
    required: false,
    value: "",
  },
  {
    label: "Genre(s)",
    inputType: "text",
    placeholder: "",
    required: false,
    value: "",
  },
  {
    label: "Year",
    inputType: "text",
    placeholder: "",
    required: false,
    value: "",
  },
];
