export const mockUsersList = [
  { name: "Kenzo Tenma", reviews: "666", recommends: "4", id: 1 },
  { name: "UWU Tenma", reviews: "67", recommends: "32", id: 2 },
  { name: "Cool Tenma", reviews: "1000", recommends: "992", id: 3 },
  { name: "Angry Tenma", reviews: "99", recommends: "1000", id: 4 },
  { name: "Dr. Tenma", reviews: "2", recommends: "0", id: 5 },
  { name: "Depressed Tenma", reviews: "5", recommends: "3", id: 6 },
];

export const mockAnimeList = [
  {
    id: 1,
    title: "Monster",
    description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    imgURL: "https://cdn.myanimelist.net/images/anime/10/18793.jpg",
    views: 13,
    likes: 2,
    reviews: 1,
    genres: ["horror", "psychological"],
  },
  {
    id: 2,
    title: "Summertime Render",
    description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    imgURL: "https://cdn.myanimelist.net/images/anime/1120/120796.jpg",
    views: 2,
    likes: 2,
    reviews: 0,
    genres: ["horror", "thriller"],
  },
  {
    id: 3,
    title: "Ergo Proxy",
    description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    imgURL: "https://cdn.myanimelist.net/images/anime/1183/136187.jpg",
    views: 1,
    likes: 1,
    reviews: 1,
    genres: ["mystery", "scifi"],
  },
  {
    id: 4,
    title: "Jujutsu Kaisen",
    description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
    imgURL: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    views: 12,
    likes: 10,
    reviews: 4,
    genres: ["action", "fantasy"],
  },
];
